#!/usr/bin/env bash

rm -rvf MeshTest.txt
rm -rvf fort.*
rm -rvf *.ini
rm -rvf *.data~
rm -rvf *.vfem
rm -rvf *.DAPA
rm -rvf *.dat
rm -rvf *.db
rm -rvf *.out
rm -rvf *.vfem
rm -rvf *.f3d
rm -rvf *.cond2d
rm -rvf *.evalbfout
rm -rvf *.plotbf
rm -rvf *.sol
rm -rvf *.bhdatal
rm -rvf *.cadatal
rm -rvf *.hgdatal
rm -rvf *.madatal
rm -rvf *.xml
